<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qimpressgast"
    nsURI="http://q-impress.eu/qimpressgast" nsPrefix="qimpressgast">
  <eClassifiers xsi:type="ecore:EClass" name="GASTBehaviour">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blockstatement" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//Block"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gastbehaviourstub" ordered="false"
        eType="ecore:EClass ../../eu.qimpress.samm/model/samm.ecore#//behaviour/GastBehaviourStub"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GASTBehaviourRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gastbehaviour" ordered="false"
        upperBound="-1" eType="#//GASTBehaviour" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
