/**
 * generated by Xtext
 */
package org.somox.metrics.dsl.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content
 * assistant
 */
@SuppressWarnings("all")
public class MetricDSLProposalProvider extends AbstractMetricDSLProposalProvider {
}
