<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="seff2javaast" nsURI="http://www.somox.org/seff2method/1.0" nsPrefix="org.somox">
  <eClassifiers xsi:type="ecore:EClass" name="SEFF2MethodMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blockstatement" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//statements/StatementListContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seff" ordered="false" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/ServiceEffectSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SEFF2JavaAST">
    <eStructuralFeatures xsi:type="ecore:EReference" name="seff2MethodMappings" ordered="false"
        upperBound="-1" eType="#//SEFF2MethodMapping" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
