/*
 * generated by Xtext
 */
package org.somox.metrics.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MetricDSLUiModule extends org.somox.metrics.dsl.ui.AbstractMetricDSLUiModule {
    public MetricDSLUiModule(final AbstractUIPlugin plugin) {
        super(plugin);
    }
}
