/*
 * generated by Xtext
 */
package org.somox.metrics.dsl;

import java.util.Properties;

import org.eclipse.xtext.Constants;
import org.eclipse.xtext.service.DefaultRuntimeModule;

import com.google.inject.Binder;
import com.google.inject.name.Names;

/**
 * Manual modifications go to {org.somox.metrics.dsl.MetricDSLRuntimeModule}
 */
@SuppressWarnings("all")
public abstract class AbstractMetricDSLRuntimeModule extends DefaultRuntimeModule {

    protected Properties properties = null;

    @Override
    public void configure(final Binder binder) {
        this.properties = this.tryBindProperties(binder, "org/somox/metrics/dsl/MetricDSL.properties");
        super.configure(binder);
    }

    public void configureLanguageName(final Binder binder) {
        binder.bind(String.class).annotatedWith(Names.named(Constants.LANGUAGE_NAME))
                .toInstance("org.somox.metrics.dsl.MetricDSL");
    }

    public void configureFileExtensions(final Binder binder) {
        if (this.properties == null || this.properties.getProperty(Constants.FILE_EXTENSIONS) == null) {
            binder.bind(String.class).annotatedWith(Names.named(Constants.FILE_EXTENSIONS)).toInstance("metrics");
        }
    }

    // contributed by org.eclipse.xtext.generator.grammarAccess.GrammarAccessFragment
    public Class<? extends org.eclipse.xtext.IGrammarAccess> bindIGrammarAccess() {
        return org.somox.metrics.dsl.services.MetricDSLGrammarAccess.class;
    }

    // contributed by org.eclipse.xtext.generator.serializer.SerializerFragment
    @Override
    public Class<? extends org.eclipse.xtext.serializer.sequencer.ISemanticSequencer> bindISemanticSequencer() {
        return org.somox.metrics.dsl.serializer.MetricDSLSemanticSequencer.class;
    }

    // contributed by org.eclipse.xtext.generator.serializer.SerializerFragment
    public Class<? extends org.eclipse.xtext.serializer.sequencer.ISyntacticSequencer> bindISyntacticSequencer() {
        return org.somox.metrics.dsl.serializer.MetricDSLSyntacticSequencer.class;
    }

    // contributed by org.eclipse.xtext.generator.serializer.SerializerFragment
    @Override
    public Class<? extends org.eclipse.xtext.serializer.ISerializer> bindISerializer() {
        return org.eclipse.xtext.serializer.impl.Serializer.class;
    }

    // contributed by org.eclipse.xtext.generator.parser.antlr.XtextAntlrGeneratorFragment
    public Class<? extends org.eclipse.xtext.parser.IParser> bindIParser() {
        return org.somox.metrics.dsl.parser.antlr.MetricDSLParser.class;
    }

    // contributed by org.eclipse.xtext.generator.parser.antlr.XtextAntlrGeneratorFragment
    @Override
    public Class<? extends org.eclipse.xtext.parser.ITokenToStringConverter> bindITokenToStringConverter() {
        return org.eclipse.xtext.parser.antlr.AntlrTokenToStringConverter.class;
    }

    // contributed by org.eclipse.xtext.generator.parser.antlr.XtextAntlrGeneratorFragment
    public Class<? extends org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider> bindIAntlrTokenFileProvider() {
        return org.somox.metrics.dsl.parser.antlr.MetricDSLAntlrTokenFileProvider.class;
    }

    // contributed by org.eclipse.xtext.generator.parser.antlr.XtextAntlrGeneratorFragment
    public Class<? extends org.eclipse.xtext.parser.antlr.Lexer> bindLexer() {
        return org.somox.metrics.dsl.parser.antlr.internal.InternalMetricDSLLexer.class;
    }

    // contributed by org.eclipse.xtext.generator.parser.antlr.XtextAntlrGeneratorFragment
    public com.google.inject.Provider<org.somox.metrics.dsl.parser.antlr.internal.InternalMetricDSLLexer> provideInternalMetricDSLLexer() {
        return org.eclipse.xtext.parser.antlr.LexerProvider
                .create(org.somox.metrics.dsl.parser.antlr.internal.InternalMetricDSLLexer.class);
    }

    // contributed by org.eclipse.xtext.generator.parser.antlr.XtextAntlrGeneratorFragment
    public void configureRuntimeLexer(final com.google.inject.Binder binder) {
        binder.bind(org.eclipse.xtext.parser.antlr.Lexer.class)
                .annotatedWith(com.google.inject.name.Names.named(org.eclipse.xtext.parser.antlr.LexerBindings.RUNTIME))
                .to(org.somox.metrics.dsl.parser.antlr.internal.InternalMetricDSLLexer.class);
    }

    // contributed by org.eclipse.xtext.generator.parser.antlr.XtextAntlrGeneratorFragment
    @Override
    public Class<? extends org.eclipse.xtext.parser.antlr.ITokenDefProvider> bindITokenDefProvider() {
        return org.eclipse.xtext.parser.antlr.AntlrTokenDefProvider.class;
    }

    // contributed by org.eclipse.xtext.generator.validation.ValidatorFragment
    @org.eclipse.xtext.service.SingletonBinding(eager = true)
    public Class<? extends org.somox.metrics.dsl.validation.MetricDSLValidator> bindMetricDSLValidator() {
        return org.somox.metrics.dsl.validation.MetricDSLValidator.class;
    }

    // contributed by org.eclipse.xtext.generator.scoping.AbstractScopingFragment
    @Override
    public Class<? extends org.eclipse.xtext.scoping.IScopeProvider> bindIScopeProvider() {
        return org.somox.metrics.dsl.scoping.MetricDSLScopeProvider.class;
    }

    // contributed by org.eclipse.xtext.generator.scoping.AbstractScopingFragment
    public void configureIScopeProviderDelegate(final com.google.inject.Binder binder) {
        binder.bind(org.eclipse.xtext.scoping.IScopeProvider.class)
                .annotatedWith(com.google.inject.name.Names
                        .named(org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider.NAMED_DELEGATE))
                .to(org.eclipse.xtext.scoping.impl.ImportedNamespaceAwareLocalScopeProvider.class);
    }

    // contributed by org.eclipse.xtext.generator.scoping.AbstractScopingFragment
    public void configureIgnoreCaseLinking(final com.google.inject.Binder binder) {
        binder.bindConstant().annotatedWith(org.eclipse.xtext.scoping.IgnoreCaseLinking.class).to(false);
    }

    // contributed by org.eclipse.xtext.generator.exporting.QualifiedNamesFragment
    @Override
    public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
        return org.eclipse.xtext.naming.DefaultDeclarativeQualifiedNameProvider.class;
    }

    // contributed by org.eclipse.xtext.generator.builder.BuilderIntegrationFragment
    @Override
    public Class<? extends org.eclipse.xtext.resource.IContainer.Manager> bindIContainer$Manager() {
        return org.eclipse.xtext.resource.containers.StateBasedContainerManager.class;
    }

    // contributed by org.eclipse.xtext.generator.builder.BuilderIntegrationFragment
    public Class<? extends org.eclipse.xtext.resource.containers.IAllContainersState.Provider> bindIAllContainersState$Provider() {
        return org.eclipse.xtext.resource.containers.ResourceSetBasedAllContainersStateProvider.class;
    }

    // contributed by org.eclipse.xtext.generator.builder.BuilderIntegrationFragment
    @Override
    public void configureIResourceDescriptions(final com.google.inject.Binder binder) {
        binder.bind(org.eclipse.xtext.resource.IResourceDescriptions.class)
                .to(org.eclipse.xtext.resource.impl.ResourceSetBasedResourceDescriptions.class);
    }

    // contributed by org.eclipse.xtext.generator.builder.BuilderIntegrationFragment
    @Override
    public void configureIResourceDescriptionsBuilderScope(final com.google.inject.Binder binder) {
        binder.bind(org.eclipse.xtext.resource.IResourceDescriptions.class)
                .annotatedWith(com.google.inject.name.Names
                        .named(org.eclipse.xtext.resource.impl.ResourceDescriptionsProvider.NAMED_BUILDER_SCOPE))
                .to(org.eclipse.xtext.resource.impl.ResourceSetBasedResourceDescriptions.class);
    }

    // contributed by org.eclipse.xtext.generator.generator.GeneratorFragment
    public Class<? extends org.eclipse.xtext.generator.IGenerator> bindIGenerator() {
        return org.somox.metrics.dsl.generator.MetricDSLGenerator.class;
    }

    // contributed by org.eclipse.xtext.generator.formatting.FormatterFragment
    @Override
    public Class<? extends org.eclipse.xtext.formatting.IFormatter> bindIFormatter() {
        return org.somox.metrics.dsl.formatting.MetricDSLFormatter.class;
    }

    // contributed by org.eclipse.xtext.generator.types.TypesGeneratorFragment
    public java.lang.ClassLoader bindClassLoaderToInstance() {
        return this.getClass().getClassLoader();
    }

    // contributed by org.eclipse.xtext.generator.types.TypesGeneratorFragment
    public org.eclipse.xtext.common.types.TypesFactory bindTypesFactoryToInstance() {
        return org.eclipse.xtext.common.types.TypesFactory.eINSTANCE;
    }

    // contributed by org.eclipse.xtext.generator.types.TypesGeneratorFragment
    public Class<? extends org.eclipse.xtext.common.types.access.IJvmTypeProvider.Factory> bindIJvmTypeProvider$Factory() {
        return org.eclipse.xtext.common.types.access.ClasspathTypeProviderFactory.class;
    }

    // contributed by org.eclipse.xtext.generator.types.TypesGeneratorFragment
    public Class<? extends org.eclipse.xtext.common.types.xtext.AbstractTypeScopeProvider> bindAbstractTypeScopeProvider() {
        return org.eclipse.xtext.common.types.xtext.ClasspathBasedTypeScopeProvider.class;
    }

    // contributed by org.eclipse.xtext.generator.types.TypesGeneratorFragment
    @Override
    public Class<? extends org.eclipse.xtext.scoping.IGlobalScopeProvider> bindIGlobalScopeProvider() {
        return org.eclipse.xtext.common.types.xtext.TypesAwareDefaultGlobalScopeProvider.class;
    }

}
